"""
Django settings for the project.
Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import sys

from dotenv import load_dotenv


# ---------------------------------------------------------------------------- #
#                                     BASE                                     #
# ---------------------------------------------------------------------------- #
# Load environment variables from .env file.
load_dotenv()

# Load the secret key from the environment variables.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# Flag to determine if the project is running in a development environment.
# WARNING: don't run with debug turned on in production!
DEBUG = True

# Flag to determine if the project is running in a testing environment.
TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

# Helper constant to refer to the project root directory.
# (e.g. to build paths inside the project like this: BASE_DIR / 'subdir'.)
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------- #
#                                  APPLICATION                                 #
# ---------------------------------------------------------------------------- #

# https://docs.djangoproject.com/en/4.2/ref/settings/#allowed-hosts
ALLOWED_HOSTS = []

# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# https://docs.djangoproject.com/en/4.2/ref/settings/#installed-apps
INSTALLED_APPS = [
    # DJANGO
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # THIRD-PARTY

    # PROJECT
    'apps.core.apps.CoreConfig',
]

# https://docs.djangoproject.com/en/4.2/ref/settings/#middleware
MIDDLEWARE = [
    # DJANGO
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-ROOT_URLCONF
ROOT_URLCONF = 'config.urls'

# https://docs.djangoproject.com/en/4.2/ref/settings/#templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# https://docs.djangoproject.com/en/4.2/ref/settings/#wsgi-application
WSGI_APPLICATION = 'config.wsgi.application'

# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------------------------------------------------- #
#                                AUTHENTICATION                                #
# ---------------------------------------------------------------------------- #

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-user-model
AUTH_USER_MODEL = 'core.User'

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------- #
#                             INTERNATIONALIZATION                             #
# ---------------------------------------------------------------------------- #

# https://docs.djangoproject.com/en/4.2/ref/settings/#language-code
LANGUAGE_CODE = 'en-us'

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TIME_ZONE
TIME_ZONE = 'UTC'

# https://docs.djangoproject.com/en/4.2/ref/settings/#language-code
USE_I18N = True

# https://docs.djangoproject.com/en/4.2/ref/settings/#use-tz
USE_TZ = True


# ---------------------------------------------------------------------------- #
#                                 STATIC FILES                                 #
# ---------------------------------------------------------------------------- #

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STATIC_URL
STATIC_URL = 'static/'

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STATICFILES_DIRS
STATICFILES_DIRS = [
    BASE_DIR / os.path.join('config', 'static'),
]

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STATIC_ROOT
STATIC_ROOT = BASE_DIR / 'staticfiles'
